version: "3.8"

services:
  frontend:
     image: panidharpsv77/quiz-frontend:latest 
    pull_policy: always
    container_name: react_app
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    
    image: panidharpsv77/quiz-backend:latest
    pull_policy: always
    container_name: spring_boot_app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/clg
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 301112
